server:
  port: 81

spring:
  redis:
    timeout: 3s
    lettuce:
      pool:
        # 连接池的最大活动连接数量，使用负值无限制
        max-active: 20
        # 连接池的最大空闲连接数量，使用负值表示无限数量的空闲连接
        max-idle: 10
        # 连接池最大阻塞等待时间，使用负值表示没有限制
        max-wait: -1s
        # 最小空闲连接数量，使用正值才有效果
        min-idle: 5
    host: ${REDIS_HOST}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}

court:
  address: jorbcetd.court.ektdecao.3kwdsc3h.com
